{
 "title": "Application workload",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total pods(by phase)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(phase) (kube_pod_status_phase{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restart Rate",
   "type": "timeseries",
   "description": "This query calculates the rate of container restarts over the last hour, grouped by namespace, which helps identify unstable applications.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, pod) (increase(kube_pod_container_status_restarts_total[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 CPU-consuming pods",
   "type": "timeseries",
   "description": "This identifies the pods with the highest CPU usage over the last 5 minutes. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) by (pod, namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod availability (non-running pods)",
   "type": "timeseries",
   "description": "To get the count of pods that are not in the Running phase, useful for detecting deployment issues.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_status_phase{phase!=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}