{
 "title": "Cluster Overview",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Memory (avg %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU (avg %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg((1 - avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total pods(by phase)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(phase) (kube_pod_status_phase{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (kube_node_status_condition{condition=\"Ready\", status=\"true\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum by(status) (kube_node_status_condition{condition=\"Ready\", status=\"false\"})",
     "legendFormat": "Not Ready"
    },
    {
     "expr": "sum by(status) (kube_node_status_condition{status=\"unknown\", condition=\"Ready\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "kube-apiserver request error rate (5xx)",
   "type": "timeseries",
   "description": "To track the rate of API server errors per second over the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"5..\"}[5m]))\r\n",
     "legendFormat": "apiserver 5xx per second"
    }
   ]
  },
  {
   "title": "kube scheduler pending pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}