{
 "title": "Node Health",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Node Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (kube_node_status_condition{condition=\"Ready\", status=\"true\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum by(status) (kube_node_status_condition{condition=\"Ready\", status=\"false\"})",
     "legendFormat": "Not Ready"
    },
    {
     "expr": "sum by(status) (kube_node_status_condition{status=\"unknown\", condition=\"Ready\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance) (100 * (1 - (node_filesystem_avail_bytes{fstype!~\"tmpfs|devtmpfs|overlay\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|devtmpfs|overlay\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (kube_node_status_condition{condition=\"DiskPressure\", status=\"false\"})",
     "legendFormat": "No Disk Pressure"
    },
    {
     "expr": "sum by(status) (kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"})",
     "legendFormat": "Disk Pressure"
    },
    {
     "expr": "sum by(status) (kube_node_status_condition{condition=\"DiskPressure\", status=\"unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  }
 ]
}